### ISSUE TITLE
Demo screenshot

### ISSUE THREAD

**Issue by HaNdTriX** [webextension-toolbox/generator-web-extension#13]
Create a demo screenshot.gif.

https://asciinema.org/

**Comment by balcsida** [comment]
Hi!

If I understand correctly, you would like to have a gif that shows the WebExtension Generator when it works.
Would it be feasible for you if I close this issue here and we actually have an embedded asciinema on https://webextension-toolbox.github.io (and maybe make a gif and link to the README.md here)?

**Comment by HaNdTriX** [comment]
I thought about something like this: https://github.com/HaNdTriX/generator-chrome-extension-kickstart

[ ] * add animated gif image to assets directory
[ ] * link it from assets directory

I don't think we need an extra gitpage for that.
